# Generated by Django 5.0.6 on 2024-11-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('JF', 'Job Finder'), ('JP', 'Job Poster'), ('Ad', 'Admin')], default='JF', max_length=2),
        ),
    ]
