# Generated by Django 5.0.6 on 2024-11-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_resume_url_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
