# Generated by Django 5.0.6 on 2024-11-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jobcategory_user_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prfile_pic_url',
            new_name='profile_pic_url',
        ),
    ]
