# Generated by Django 5.0.6 on 2024-12-04 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_prfile_pic_url_user_profile_pic_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=299)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('FT', 'Full time'), ('PT', 'Part time'), ('CT', 'Contract')], max_length=2)),
                ('location', models.CharField(max_length=399)),
                ('salary_range', models.CharField(default='Negotiable', max_length=50)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='OP', max_length=2)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(null=True)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcategory')),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
