# Generated by Django 5.0.6 on 2024-12-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_application_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
