# Generated by Django 5.0.6 on 2024-12-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_update_at_job_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('ACP', 'Accepted'), ('REJ', 'Rejected')], default='PND', max_length=3),
        ),
    ]
